### ISSUE TITLE
blas, lapack

### ISSUE THREAD

**Issue by marcosci** [pat-s/antergos_setup_guide#1]
Maybe include in the R setup section a hint on how to exchange the numeric libraries with openblas/intel-mkl?

**Comment by pat-s** [comment]
Thanks for the hint! Happy to include it. I assume this results in computational speed ups? Haven't dived into this yet. 
Can you shortly outline the advantages? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcosci** [comment]
Both of them are just optimized BLAS libraries, too my knowledge mainly making multi-threading available.
Here is a recent benchmark comparing them:

http://pacha.hk/2017-12-02_why_is_r_slow.html

Basically the only thing you have to do is using `pac install openblas` (https://wiki.archlinux.org/index.php/R#OpenBLAS) and check if everything is correct (`utils::sessionInfo()`). The fact that it s a pain to change the numeric libraries in windows (I never accomplished it) and a one-liner under linux is maybe another point for your comparison :)

**Comment by pat-s** [comment]
Nice! Was not aware that these libs have such a great influence on runtime. 

I'll change it later on right away :+1:

**Comment by marcosci** [comment]
:-)

maybe also include pac install r under section 4? that step could be misleading, using ccache and rstudio without first installing r.
