### ISSUE TITLE
tcl, tk dependencies for R

### ISSUE THREAD

**Issue by MilesMcBain** [pat-s/antergos_setup_guide#2]
When I first ran R in my new Antergos install I got an error trying to install packages because the mirror selection dialogue could not be launched:

`Error: .onLoad failed in loadNamespace() for 'tcltk', details: call: dyn.load(file, DLLpath = DLLpath, ...) error: unable to load shared object '/usr/lib/R/library/tcltk/libs/tcltk.so'`

There's a bit of outdated info around online about this. It turns out there are two packages: `tcl` and `tk` that need to be installed. My install came only with `tcl`.

**Comment by pat-s** [comment]
Right, that's a dep. Wondering which other package installs it as a dep so that I did not notice when arriving at that point. 
Will add it 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
