### ISSUE TITLE
Issue with R and new version of gcc-fortran?

### ISSUE THREAD

**Issue by MilesMcBain** [pat-s/antergos_setup_guide#3]
I upgraded my `gcc-fortran` and now R will not start with: `/usr/lib64/R/bin/exec/R: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory`

`ls /usr/lib/libgfortran.so.*` returns:
```
/usr/lib/libgfortran.so.5  /usr/lib/libgfortran.so.5.0.0
```
So I think this means I am in trouble. I'd avoid taking the new version of gcc-fortran unless you know how to resolve this.

**Comment by MilesMcBain** [comment]
It turns out it is libopenblas-lapack from the AUR that is yet to be rebuilt using the new version. I uninstalling this package and R, re-installed R and it worked.

**Comment by pat-s** [comment]
Yes, you need to (only) reinstall R (no matter which version you have) as `gcc-fortran` is a dep and R doesn't find it anymore in the system after the upgrade :)
